#!/bin/bash

chown -R www-data:www-data /var/www
#mkdir -p /var/www/html/consoleAPI
#ln -s /var/www/html/restfulapi/ /var/www/html/consoleAPI/api
timezone=$(cat /etc/timezone)
sed -i "s|;date.timezone =|date.timezone = $timezone|" /etc/php5/apache2/php.ini

mkdir -p /usr/local/skysql/cache/api
chown -R www-data:www-data /usr/local/skysql/cache
mkdir -p /usr/local/skysql/backups
chown -R www-data:www-data /usr/local/skysql/backups
mkdir -p /var/www/.ssh
touch /var/www/.ssh/known_hosts
chown www-data:www-data /var/www/.ssh/known_hosts

mkdir -p /usr/local/skysql/SQLite/AdminConsole
chown -R www-data:www-data /usr/local/skysql/SQLite

if [ ! -f /var/www/.ssh/id_rsa.pub ] ; then
	ssh-keygen -q -f /var/www/.ssh/id_rsa -N "" 
	chown www-data:www-data /var/www/.ssh/id_rsa /var/www/.ssh/id_rsa.pub
fi

# disabling selinux! TO BE FIXED! 
echo 0 >/selinux/enforce
# permanently disabling SELinux: on GRUB configuration [/etc/grub/...]?

# add firewall rule to allow port 80 
iptables -I INPUT -p tcp --dport 80 -j ACCEPT
iptables-save > /etc/iptables/rules.v4

a2enmod rewrite
a2enmod proxy_ajp
apacheMod=$(sed 's/[]\/()$*.^|[]/\\&/g' /etc/apache2/conf.d/skysql_rewrite.conf | sed -e ':a;N;$!ba;s/\n/\\\n/g')
if ! grep -q ProxyPass /etc/apache2/sites-enabled/000-default ; then
    sed -i "/\/VirtualHost/i $apacheMod" /etc/apache2/sites-enabled/000-default
fi
service apache2 restart

service atd start
update-rc.d atd defaults
