#!/bin/bash

chown -R www-data:www-data /var/www
#mkdir -p /var/www/html/consoleAPI
#ln -s /var/www/html/restfulapi/ /var/www/html/consoleAPI/api
timezone=$(cat /etc/timezone)
sed -i "s|;date.timezone =|date.timezone = $timezone|" /etc/php5/apache2/php.ini

mkdir -p /usr/local/skysql/cache/api
chown -R www-data:www-data /usr/local/skysql/cache
mkdir -p /var/www/.ssh
touch /var/www/.ssh/known_hosts
chown www-data:www-data /var/www/.ssh/known_hosts

mkdir -p /usr/local/skysql/SQLite/AdminConsole
chown -R www-data:www-data /usr/local/skysql/SQLite

mkdir -p /usr/local/skysql/config

if [ ! -f /var/www/.ssh/id_rsa.pub ] ; then
	ssh-keygen -q -f /var/www/.ssh/id_rsa -N "" 
	chown www-data:www-data /var/www/.ssh/id_rsa /var/www/.ssh/id_rsa.pub
fi

# Not overwriting existing API configurations
if [ ! -f /etc/skysqlmgr/api.ini ] ; then
	# Generating API key for the local scripts
	newKey=$(echo $RANDOM$(date)$RANDOM | md5sum | cut -f1 -d" ")
	
	componentID=2
	keyString="${componentID} = \"${newKey}\""

	# Registering key on components.ini file
	componentFile=/usr/local/skysql/config/components.ini
	grep "^${componentID} = \"" ${componentFile} &>/dev/null
	if [ "$?" != "0" ] ; then
		echo $keyString >> $componentFile
	fi
	
	# Registering key on api.ini file
	grep "^${componentID} = \"" /etc/skysqlmgr/api.ini.template &>/dev/null
	if [ "$?" != "0" ] ; then
		sed -i "/^\[apikeys\]$/a $keyString" /etc/skysqlmgr/api.ini.template
	fi

	# Generating API key for GREX
	newKey=$(echo $RANDOM$(date)$RANDOM | md5sum | cut -f1 -d" ")
	
	componentID=4
	keyString="${componentID} = \"${newKey}\""

	# Registering key on api.ini file
	grep "^${componentID} = \"" /etc/skysqlmgr/api.ini.template &>/dev/null
	if [ "$?" != "0" ] ; then
		sed -i "/^\[apikeys\]$/a $keyString" /etc/skysqlmgr/api.ini.template
	fi	

	# Creating api.ini file
	cp /etc/skysqlmgr/api.ini.template /etc/skysqlmgr/api.ini
fi

# disabling selinux! TO BE FIXED! 
echo 0 >/selinux/enforce
# permanently disabling SELinux: on GRUB configuration [/etc/grub/...]?

# add firewall rule to allow port 80 
iptables -I INPUT -p tcp --dport 80 -j ACCEPT
iptables-save > /etc/iptables/rules.v4

a2enmod rewrite
service apache2 restart

service atd start
update-rc.d atd defaults

